name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: PHP Unit Tests

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Make .env
        run: |
          echo "JUNGLE_BOOK_API_KEY=$JUNGLE_BOOK_API_KEY" > .env
        env:
          JUNGLE_BOOK_API_KEY: ${{ secrets.JUNGLE_BOOK_API_KEY }}

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
      # Docs: https://getcomposer.org/doc/articles/scripts.md

      - name: Run test suite
        run: composer run test
